// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfNWPAXeiPB-s1i0EOCUlT2us-KI-M3mw',
    appId: '1:601882385577:web:d49706f40200b62def5db8',
    messagingSenderId: '601882385577',
    projectId: 'gsayubams123',
    authDomain: 'gsayubams123.firebaseapp.com',
    storageBucket: 'gsayubams123.appspot.com',
    measurementId: 'G-VKJ7P4TEZH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9zLfUVpgNSXX0C0BDwtn8LSV0dlMz7F4',
    appId: '1:601882385577:android:d73cd5d5fe60d2edef5db8',
    messagingSenderId: '601882385577',
    projectId: 'gsayubams123',
    storageBucket: 'gsayubams123.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJwhMgcqSzRe8f9evNmb2JOY_E_AbfDiA',
    appId: '1:601882385577:ios:ecf30700f9d3a0ddef5db8',
    messagingSenderId: '601882385577',
    projectId: 'gsayubams123',
    storageBucket: 'gsayubams123.appspot.com',
    iosClientId: '601882385577-tbusu2vr2nr5eqtd651hbhfou6cvn0bl.apps.googleusercontent.com',
    iosBundleId: 'com.dotdev.inc.ams',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJwhMgcqSzRe8f9evNmb2JOY_E_AbfDiA',
    appId: '1:601882385577:ios:48afd481336ec164ef5db8',
    messagingSenderId: '601882385577',
    projectId: 'gsayubams123',
    storageBucket: 'gsayubams123.appspot.com',
    iosClientId: '601882385577-7466t1t3j2vl627p969co5bdlitkdcuh.apps.googleusercontent.com',
    iosBundleId: 'com.dotdev.inc.ams.RunnerTests',
  );
}
